version: '3'
services:
  web0:
    container_name: web0
    build:
      context: /web0
      dockerfile: Dockerfile
    depends_on:
      - agency
    restart: always
    networks:
      - test
    expose:
      - "80"
  web1:
    container_name: web1
    build:
      context: /web1
      dockerfile: Dockerfile
    depends_on:
      - agency
    restart: always
    networks:
      - test
    expose:
      - "80"
  web2:
    container_name: web2
    build:
      context: /web2
      dockerfile: Dockerfile
    depends_on:
      - agency
    restart: always
    networks:
      - test
    expose:
      - "80"
  agency:
    container_name: agency
    build:
      context: /agency
      dockerfile: Dockerfile
    ports:
      - "9010:80" #对外暴露9010端口
    restart: always
    networks:
      - test
networks:
  test:
    driver: bridge 